

target ‘BuyCar’ do

pod 'ReactiveCocoa', ‘2.5’
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage' , '3.7.3'
pod 'Masonry'
pod 'MJRefresh'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'Reachability', '~> 3.2'
pod 'IQKeyboardManager', '~> 4.0.4'


end